# Local search
local_search:
  # 是否开启本地搜索
  enable: true
  # 预加载，开启后，进入网页后会自动加载搜索文件。关闭时，只有点击搜索按钮后，才会加载搜索文件
  preload: false
  # 匹配的文章结果，默认显示最开始的 1 段结果
  top_n_per_article: 1
  # 将 html 字符串解码为可读字符串
  unescape: false
  CDN:

subtitle:
  # 调用一言网的一句話（简体）
  source: https://hitokoto.cn/

# 主页面的top_img
index_img: /img/top.jpg

# 设置为true后禁用顶部图片
disable_top_img: false

# 默认页面的top_img，如当前页未配置top_img时，则使用该配置
default_top_img:

avatar:
  # 头像地址，可以为在线地址或本地相对路径
  img: /img/avatar.jpg
  # 头像动画，为true是会一直转圈
  effect: false
