[book]
title = "Example book"
authors = ["0o0b"]
description = "The example book covers examples."

[build]
create-missing = false

[output.html]
additional-css = ["css/common.css"]

[output.html.search]
limit-results = 15
